version: "3"
services:
  Etcd-server:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
    networks:
      - CC
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - CC
  test:
    build: ./test
    networks:
      - CC
    depends_on:
      - backend
      - Etcd-server
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    networks:
      - CC
networks:
  CC:
    driver: bridge
